[rule]
author = ["Anthony Stannard"]
description = """
Detects Nmap and Nikto User Agent strings.
"""
from = "now69m"  # This is the default for elastic
name = "Web Scanner Activity - Nmap and Nikto"
risk_score = 25
severity = "low"
type = "query"

query = '''
event.dataset : zeek.http and user_agent.orginal: *Nmap* or user_agent.orginal: *Nikto*
'''


[[rule.threat]]  # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"



[rule.threat.tactic]
id = "TA0009=7"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"