name: Metrics

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                    token: ${{ secrets.GH_KEY }}
            - uses: actions/setup-python@v4
              with:
                    python-version: '3.11.4'
            - run: pip install python-dateutil
            - run: python development/toml_to_report.py
            - run: python3 development/toml_to_csv.py
            - run: |
                    git config user.name Anthony-Stannard
                    git config user.email zstannardz@hotmail.com
                    git add .
                    git commit -m "Updating Metrics"
                    git push -f